smartDormitory/smartDormitory.WEB/Areas/Admin/Models/User/AllUsersViewModel.cs
using smartDormitory.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace smartDormitory.WEB.Areas.Admin.Models
{
    public class AllUsersViewModel
    {
        public IEnumerable<UserViewModel> Users { get; set; }

        // Pagination Properties        
        public int TotalPages { get; set; }
        public int Page { get; set; } = 1;
        public int PreviousPage => this.Page ==
            1 ? 1 : this.Page - 1;
        public int NextPage => this.Page ==
            this.TotalPages ? this.TotalPages : this.Page + 1;
        public string SearchText { get; set; } = string.Empty;
        public string StatusMessage { get; set; }
    }
}

smartDormitory/smartDormitory.WEB/Areas/Admin/Models/User/UserModalViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace smartDormitory.WEB.Areas.Admin.Models
{
    public class UserModalViewModel
    {
        [Required]
        public string Id { get; set; }        

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "NewPassword")]
        public string NewPassword { get; set; }
                
        [DataType(DataType.Password)]
        [Compare("NewPassword", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

smartDormitory/smartDormitory.WEB/Areas/Admin/Models/User/UserViewModel.cs
using smartDormitory.Data.Models;
using System;

namespace smartDormitory.WEB.Areas.Admin.Models
{
    public class UserViewModel
    {
        public UserViewModel(User user)
        {
            this.Id = user.Id;
            this.UserName = user.UserName;
            this.Email = user.Email;
            this.LockoutEnd = user.LockoutEnd;
        }

        public string Id { get; set; }

        public string UserName { get; set; }

        public string Email { get; set; }

        public string Role { get; set; }

        public DateTimeOffset? LockoutEnd { get; set; }
    }
}

smartDormitory/smartDormitory.WEB/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using smartDormitory.Data.Models;
using smartDormitory.Services.Contracts;
using smartDormitory.WEB.Areas.Admin.Models;
using smartDormitory.WEB.Providers;

namespace smartDormitory.WEB.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUserService userService;
        private readonly IUserManager<User> _userManager;
        private readonly IRoleManager<IdentityRole> _roleManager;
        private readonly int Page_Size = 3;

        [TempData]
        public string StatusMessage { get; set; }

        public UsersController(IUserManager<User> userManager, IUserService userService, IRoleManager<IdentityRole> roleManager)
        {
            this._userManager = userManager;
            this.userService = userService;
            this._roleManager = roleManager;
        }

        public async Task<IActionResult> AllUsers(AllUsersViewModel viewModel)
        {
            var isTextNull = viewModel.SearchText ?? "";

            var users = await this.userService.GetUsersAsync(isTextNull, 1, Page_Size);
            viewModel.Users = users.Select(u => new UserViewModel(u));

            var totalUsers = await this.userService.GetTotalUserAsync(isTextNull);

            viewModel.TotalPages = (int)Math.Ceiling(totalUsers / (double)Page_Size);

            return View(viewModel);
        }
                
        public async Task<IActionResult> UserGrid(AllUsersViewModel viewModel)
        {
            var isTextNull = viewModel.SearchText ?? "";
            var users = await this.userService.GetUsersAsync(isTextNull, viewModel.Page, Page_Size);

            viewModel.Users = users.Select(u => new UserViewModel(u));
            var totalUsers = await this.userService.GetTotalUserAsync(isTextNull);

            viewModel.TotalPages = (int)Math.Ceiling(totalUsers / (double)Page_Size);

            
            return PartialView("_UserGrid", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LockUser(string Id)
        {
            var user = this._userManager.Users.Where(u => u.Id == Id).FirstOrDefault();

            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return RedirectToAction(nameof(AllUsers));
            }

            var enableLockOutResult = await this._userManager.SetLockoutEnabledAsync(user, true);

            if (!enableLockOutResult.Succeeded)
            {
                this.StatusMessage = "Error: Could enable the lockout on the user!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var lockOutTimeResult = await this._userManager.SetLockoutEndDateAsync(user, DateTime.Today.AddYears(10));

            if (!lockOutTimeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not add time to user's lockout!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            this.StatusMessage = "The user has been successfully locked for 10 years!";

            return View("_UserStatusMessage", this.StatusMessage);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnlockUser(string Id)
        {
            var user =  _userManager.Users.Where(u => u.Id == Id).FirstOrDefault();

            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var lockoutTimeResult = await this._userManager.SetLockoutEndDateAsync(user, DateTime.Now);

            if (!lockoutTimeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not add time to user's lockout!";
                return View("_UserStatusMessage", this.StatusMessage);
            }
            
            this.StatusMessage = "The user has been successfully unlocked!";
            return View("_UserStatusMessage", this.StatusMessage);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePassword(UserModalViewModel input)
        {
            var user = _userManager.Users.Where(u => u.Id == input.Id).FirstOrDefault();
            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            foreach (var validator in _userManager.PasswordValidators)
            {
                var result = await validator.ValidateAsync(_userManager.Instance, user, input.ConfirmPassword);
                if (!result.Succeeded)
                {
                    this.StatusMessage = $"Error: {string.Join(" ", result.Errors.Select(e => e.Description)).Replace(".", "!")}";
                    return View("_UserStatusMessage", this.StatusMessage);
                }
            }

            if (!ModelState.IsValid)
            {
                this.StatusMessage = "Error: Passwords do not match!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var removeResult = await _userManager.RemovePasswordAsync(user);
            if (!removeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not remove the old password!";
                return View("_UserStatusMessage", this.StatusMessage);
            }
            var addPasswordResult = await _userManager.AddPasswordAsync(user, input.NewPassword);
            if (!addPasswordResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not change the password!";
                return View("_UserStatusMessage", this.StatusMessage);
            }
            this.StatusMessage = "The user's password has been changed!";
            return View("_UserStatusMessage", this.StatusMessage);
        }

        [HttpPost]
        public async Task<JsonResult> GetRole(string Id)
        {
            var user = this._userManager.Users.Where(u => u.Id == Id).FirstOrDefault();
            if (user is null)
            {
                return new JsonResult("Error: User not found!");
            }

            var role = await this._userManager.GetRolesAsync(user);
            var myRole = role.FirstOrDefault();

            return new JsonResult(myRole);
        }

        [HttpGet]
        public JsonResult GetAllExistsRoles()
        {
            var roles = this._roleManager.Roles.ToList();

            return new JsonResult(roles);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangeRole(string Id, string Role)
        {
            if (string.IsNullOrEmpty(Id))
            {
                this.StatusMessage = "Error: User's Id is incorrect!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            if (string.IsNullOrEmpty(Role))
            {
                this.StatusMessage = "Error: Role is incorrect!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var user = this._userManager.Users.Where(u => u.Id == Id).FirstOrDefault();

            if (user is null)
            {
                this.StatusMessage = "Error: User not found!";
                return View("_UserStatusMessage", this.StatusMessage);
            }
            
            var roleCheck = await this._roleManager.RoleExistsAsync(Role);
            if (!roleCheck)
            {
                this.StatusMessage = "Error: Role not found!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var userRole = await this._userManager.GetRolesAsync(user);
            var currentRole = userRole.FirstOrDefault();

            var removeResult = await this._userManager.RemoveFromRoleAsync(user, currentRole);
            if (!removeResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not remove the old role!";
                return View("_UserStatusMessage", this.StatusMessage);
            }

            var addRoleResult = await this._userManager.AddToRoleAsync(user, Role);
            if (!addRoleResult.Succeeded)
            {
                this.StatusMessage = "Error: Could not change the role!";
                return View("_UserStatusMessage", this.StatusMessage);
            }
            this.StatusMessage = "The user's role has been changed!";
            return View("_UserStatusMessage", this.StatusMessage);
        }
    }
}

smartDormitory/smartDormitory.WEB/Controllers/SensorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using smartDormitory.Data.Models;
using smartDormitory.Services.Contracts;
using smartDormitory.WEB.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace smartDormitory.WEB.Controllers
{
    public class SensorsController : Controller
    {
        private readonly IICBApiSensorsService apiSensorsService;
        private readonly IUserSensorService userSensorService;
        private readonly UserManager<User> userManager;
        private const int Page_Size = 5;

        public SensorsController(IICBApiSensorsService apiSensorsService, IUserSensorService userSensorService, UserManager<User> userManager)
        {
            this.apiSensorsService = apiSensorsService ?? throw new ArgumentNullException(nameof(apiSensorsService));
            this.userSensorService = userSensorService ?? throw new ArgumentNullException(nameof(userSensorService));
            this.userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
        }

        public async Task<IActionResult> RegisterSensors()
        {
            try
            {
                await this.apiSensorsService.UpdateSensorsAsync();
                return Ok();
            }

            catch (HttpRequestException httpRequestException)
            {
                return BadRequest($"Error getting sensor information from ICBApi: {httpRequestException.Message}");
            }
        }

        [Authorize]
        public IActionResult AllSensorTypes(SensorTypesViewModel model)
        {
            if (model.SearchText == null)
            {
                model.Sensors = this.apiSensorsService.ListAllSensors(model.Page, Page_Size);
                model.TotalPages = (int)Math.Ceiling(this.apiSensorsService.Total() / (double)Page_Size);
            }
            else
            {
                model.Sensors = this.apiSensorsService.ListByContainingText(model.SearchText, model.Page, Page_Size);
                model.TotalPages = (int)Math.Ceiling(this.apiSensorsService.TotalContainingText(model.SearchText) / (double)Page_Size);
            }

            return View(model);
        }

        [Authorize]
        public IActionResult AllSensorTypesGrid(SensorTypesViewModel model)
        {
            if (model.SearchText == null)
            {
                model.Sensors = this.apiSensorsService.ListAllSensors(model.Page, Page_Size);
                model.TotalPages = (int)Math.Ceiling(this.apiSensorsService.Total() / (double)Page_Size);
            }
            else
            {
                model.Sensors = this.apiSensorsService.ListByContainingText(model.SearchText, model.Page, Page_Size);
                model.TotalPages = (int)Math.Ceiling(this.apiSensorsService.TotalContainingText(model.SearchText) / (double)Page_Size);
            }

            return PartialView("_AllSensorTypesGrid", model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult RegisterSensor(int sensorId, string tag, string description)
        {
            var userId = userManager.GetUserId(User);

            var validationsMinMax = this.GetMinMaxValidations(description);

            var userSensorModel = new UserSensorViewModel()
            {
                Id = sensorId,
                UserId = userId,
                Tag = tag,
                ValidationsMinMax = validationsMinMax
            };

            return View(userSensorModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RegisterSensor(UserSensorViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return View(model);
            }

            await this.userSensorService.AddSensorAsync(model.UserId, model.Id, model.Name, model.Description, model.MinValue, model.MaxValue,
                 model.PollingInterval, model.Latitude, model.Longtitude, model.IsPublic, model.Alarm, model.ImageUrl);

            return RedirectToAction("Index", "Home");
        }

        private List<double> GetMinMaxValidations(string description)
        {
            var validations = new List<double>();

            string[] numbers = Regex.Split(description, @"\D+");
            foreach (string value in numbers)
            {
                if (!string.IsNullOrEmpty(value))
                {
                    validations.Add(double.Parse(value));
                }
            }
            return validations;
        }
    }
}

smartDormitory/smartDormitory.WEB/Areas/Admin/Views/Users/AllUsers.cshtml
@model AllUsersViewModel

@{
    ViewData["Title"] = "AllUsers";
}

<partial name="_UserGrid" for="@Model" />

<partial name="_UserModal" model="null" />

@section Scripts{

    <script>
jQuery.noConflict();
$('#unlockModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('whatever') // Extract info from data-* attributes
    var userId = button.data('user-id')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this)
    modal.find('.modal-title').text('Unlock "' + recipient + '"')
    modal.find('.modal-body').text('You are about to unlock "' + recipient + '", are you sure?')
    modal.find('input[name="Id"]').val(userId)
});


jQuery.noConflict();
$('#lockModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('whatever') // Extract info from data-* attributes
    var userId = button.data('user-id')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this)
    modal.find('.modal-title').text('Lock "' + recipient + '"')
    modal.find('.modal-body').text('You are about to lock "' + recipient + '", are you sure?')
    modal.find('input[name="Id"]').val(userId)
});


jQuery.noConflict();
$('#passwordModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('whatever') // Extract info from data-* attributes
    var userId = button.data('user-id')
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    var modal = $(this);
    modal.find('.modal-title').text('Change The ' + recipient + '\'s Password')
    modal.find('.modal-body input[name="Id"]').val(userId)
});

jQuery.noConflict();
$('#roleModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget) // Button that triggered the modal
    var recipient = button.data('whatever') // Extract info from data-* attributes
    var userId = button.data('user-id')
    var currRole = "";

    var modal = $(this);

    // Get current user's role!!!
    $.post('@Url.Action("GetRole", "Users")', { Id: userId }, function (data) {
        modal.find('.modal-body').text('Current role: "' + data + '".');
        currRole = data;

        // Get all exists roles!!!
        $.get('@Url.Action("GetAllExistsRoles", "Users")', function (data) {
            data.forEach((value) => {
                if (value.name != currRole) {

                    modal.find('.modal-body').append('<div>You can set "<b>' + value.name + '</b>" role!</div>');
                    modal.find('input[name="Role"]').val(value.name);
                }
            })
        }).fail(function () { });
    }).fail(function () { });
    // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
    // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
    modal.find('.modal-title').text('Change The ' + recipient + '\'s Role')
    modal.find('input[name="Id"]').val(userId)
        });
    </script>

    <script>
        $(document).on("click", ".page-item a", function () {
            $.ajax({
                url: $(this).attr("href"),                
                type: 'GET',
                cache: false,
                success: function (result) {
                    $('#content').html(result);
                }
            });
            return false;
        });
    </script>
    <partial name="_ValidationScriptsPartial" />
}

smartDormitory/smartDormitory.WEB/Areas/Admin/Views/Users/_UserGrid.cshtml
@model AllUsersViewModel

@{
    var previousDisabled = Model.Page == 1 ? "disabled" : string.Empty;
    var nextDisabled = Model.Page == Model.TotalPages ? "disabled" : string.Empty;
    var counter = 1;
}

<div id="content">
    <nav class="navbar navbar-expand-md navbar-light">
        <form asp-area="Admin" asp-action="AllUsers" asp-controller="Users" method="GET" class="form-inline">
            <input asp-for="@Model.SearchText" class="form-control mr-sm-2" type="search" placeholder="Search user by name..." aria-label="Search">
            <button class="btn my-2 my-sm-0" type="submit" id="adminDashboardButtnon">Search</button>
        </form>

    </nav>
    <table class="table table-responsive-md table-hover text-light">
        <thead>
            <tr class="text-md-center">
                <th>Number</th>
                <th>Username</th>
                <th>Email</th>
                <th>Settings</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Users.Count() == 0)
            {
                <tr class="text-md-center">
                    <td colspan="4">No data available in table</td>
                </tr>
            }
            else
            {
                foreach (var user in Model.Users)
                {
                    var unlockButtonDisabled = user.LockoutEnd < DateTimeOffset.Now ? "disabled" : string.Empty;
                    var lockButtonDisabled = user.LockoutEnd < DateTimeOffset.Now ? string.Empty : "disabled";

                    <tr class="text-md-center">
                        <td>@counter</td>
                        <td>@user.UserName</td>
                        <td>@user.Email</td>
                        <td>
                            <div class="btn-group">

                                <!--LOCK BUTTON-->
                                <div class="tooltip-inside">
                                    <button type="button" class="btn p-1 tooltip-inside" id="lockButton" data-toggle="modal" data-target="#lockModal" data-whatever="@user.UserName" data-user-id="@user.Id" @lockButtonDisabled><img src="~/images/icons8-lock-24.png" /></button>
                                    <span class="tooltiptext">Lock User</span>
                                </div>

                                <!--UNLOCK BUTTON-->
                                <div class="tooltip-inside ml-2 ">
                                    <button type="button" class="btn p-1" id="unlockButton" data-toggle="modal" data-target="#unlockModal" data-whatever="@user.UserName" data-user-id="@user.Id" @unlockButtonDisabled><img src="~/images/icons8-padlock-24.png" /></button>
                                    <span class="tooltiptext">Unlock User</span>
                                </div>

                                <!--PASSWORD BUTTON-->
                                <div class="tooltip-inside ml-2">
                                    <button type="button" class="btn p-1" id="passwordButton" data-toggle="modal" data-target="#passwordModal" data-whatever="@user.UserName" data-user-id="@user.Id"><img src="~/images/icons8-password-1-24.png" /></button>
                                    <span class="tooltiptext">Change Password</span>
                                </div>

                                <!--ROLE BUTTON-->
                                <div class="tooltip-inside ml-2">
                                    <button type="button" class="btn p-1" id="roleButton" data-toggle="modal" data-target="#roleModal" data-whatever="@user.UserName" data-user-id="@user.Id"><img src="~/images/icons8-account-24.png" /></button>
                                    <span class="tooltiptext">Change Role</span>
                                </div>

                                <!--ADD SENSOR BUTTON-->                               
                                <form asp-area="Admin" asp-controller="Sensors" asp-action="AllSensorTypes" method="post">
                                    <div class="tooltip-inside ml-2">
                                        <button type="submit" class="btn p-1" id="sensorsButton"><img src="~/images/icons8-plus-24.png" /></button>
                                        <span class="tooltiptext">Add Sensor</span>
                                    </div>
                                    <input class="text-hide" type="hidden" name="UserName" value="@user.UserName" />
                                    <input class="text-hide" type="hidden" name="UserId" value="@user.Id" />
                                </form>
                            </div>
                        </td>
                    </tr>
                    counter++;
                }
            }
        </tbody>
    </table>
    <!--PAGINATION LOGIC-->
    <nav aria-label="Page navigation example" align="center">
        <ul class="pagination">
            <li class="page-item">
                <a class="page-link @previousDisabled" href="/Admin/Users/UserGrid/?searchtext=@Model.SearchText&page=@Model.PreviousPage" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                    <span class="sr-only">Previous</span>
                </a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                <li class="page-item"><a class="page-link" href="/Admin/Users/UserGrid?searchtext=@Model.SearchText&page=@i">@i</a></li>
            }
            <li class="page-item">
                <a class="page-link @nextDisabled" href="/Admin/Users/UserGrid/?searchtext=@Model.SearchText&page=@Model.NextPage" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                    <span class="sr-only">Next</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

smartDormitory/smartDormitory.WEB/Areas/Admin/Views/Users/_UserModal.cshtml
@model UserModalViewModel
<!-- Modal -->
<!-- Lock -->
<div class="modal fade" id="lockModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Manage user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Include some text here!</p>
            </div>
            <div class="modal-footer">
                <form asp-area="Admin" asp-controller="Users" asp-action="LockUser" method="post">
                    <div>
                        <input class="text-hide" name="Id" />
                        <button type="submit" class="btn btn-danger">Lock user</button>
                    </div>
                </form>
                <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<!-- Unlock -->
<div class="modal fade" id="unlockModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Manage user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Include here some text!</p>
            </div>
            <div class="modal-footer">
                <form asp-area="Admin" asp-controller="Users" asp-action="UnlockUser" method="post">
                    <div>
                        <input class="text-hide" name="Id" />
                        <button type="submit" class="btn btn-success">Unlock user</button>
                    </div>
                </form>
                <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<!-- Password -->
<div class="modal fade" id="passwordModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Manage user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form asp-area="Admin" asp-controller="Users" asp-action="ChangePassword" method="post">
                <div class="modal-body">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div>
                        <input asp-for="Id" class="text-hide" name="Id" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewPassword"></label>
                        <input asp-for="NewPassword" class="form-control" />
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword"></label>
                        <input asp-for="ConfirmPassword" class="form-control" />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <div>
                        <button type="submit" class="btn btn-danger">Update Password</button>
                    </div>
                    <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<!-- Role -->
<div class="modal fade" id="roleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Manage user</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Include here some text!</p>
                
            </div>
            <div class="modal-footer"> 
                <form asp-area="Admin" asp-controller="Users" asp-action="ChangeRole" method="post">
                    <div>
                        <input class="text-hide" name="Id" />
                        <input class="text-hide" name="Role" />
                        <button type="submit" class="btn btn-success">Apply</button>
                    </div>
                </form>
                <button type="submit" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>